title: PulseDocs
description: "Documentation for Pulse by Devoteam"
logo: "/assets/images/pulse-logo.png"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: light
search_enabled: true
