title: PulseDocs
description: "Documentation for Pulse by Devoteam"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: light
search_enabled: true

aux_links:
  "docs.pulse.devoteam.com":
    - "http://docs.pulse.devoteam.com/"
aux_links_new_tab: true
